### ISSUE TITLE
Is the use of the HubMethodName attribute supported?

### ISSUE THREAD

**Issue by iSchlicht** [nenoNaninu/TypedSignalR.Client.TypeScript#139]
Could it be that the HubMethodName attribute is not being used and the generated proxy is pointing to the wrong hub method name?

**Comment by nenoNaninu** [comment]
To support `HubMethodNameAttribute`, the methods defined in the interface must be annotated with it. Therefore, annotating both the interface and the Hub class that implements it with the `HubMethodNameAttribute` is necessary. Since this may cause problems due to forgotten attribute annotations, we have decided not to support it.

```cs
[Hub]
public interface IMyHub
{
    [HubMethodName("method1")]
    Task<int> Add(int x, int y);
}

public class MyHub : Hub, IMyHub
{
    [HubMethodName("method1")]
    public Task<int> Add(int x, int y)
    {
        return Task.FromResult(x + y);
    }
}

```
